### ISSUE TITLE
K8s worker nodes missing AWS X-Ray IAM permission

### ISSUE THREAD

**Issue by PaulMaddox** [PaulMaddox/aws-appmesh-helm#1]
The IAM role associated with the worker nodes does not allow write access to AWS X-Ray by default, therefore no metrics are reported.

#### Temporary Workaround
Add the `AWSXRayDaemonWriteAccess` managed policy to the NodeInstance IAM role. The AWS X-Ray console will then spring into life.

#### Longer Term
Submit a PR to eksctl to add an `--xray-access` flag.

**Comment by mhausenblas** [comment]
For the record, the policy you can take from here: https://github.com/aws/aws-app-mesh-examples/blob/master/walkthroughs/eks/o11y-xray.md

**Comment by PaulMaddox** [comment]
PR opened with eksctl

**Comment by PaulMaddox** [comment]
This is now resolved as of https://github.com/PaulMaddox/aws-appmesh-helm/commit/7e18e8e75a6acb6ff5a2c7f1992180f14a0f25a5
